name: Deploy HRMS app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build \
            -t phoenix5911/HRMS-app:latest \
            --build-arg REACT_APP_NODE_ENV=production \
            --build-arg REACT_APP_SERVER_BASE_URL=${{ secrets.REACT_APP_SERVER_BASE_URL }} .
          docker push phoenix5911/HRMS-app:latest

  deploy:
    needs: build
    runs-on: self-hosted  # Your EC2 runner

    steps:
      - name: Pull image from Docker Hub
        run: docker pull phoenix5911/HRMS-app:latest

      - name: Delete old container
        run: docker rm -f HRMS-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 8080:80 --name HRMS-app-container phoenix5911/HRMS-app:latest
